# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator10.0
# cache: cocoapods
#podfile: Example/Podfile
script:
- xctool test -workspace Example/RxSegue.xcworkspace -scheme RxSegue-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
#- pod lib lint
