# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c
script:
- set -o pipefail && xcodebuild -workspace 'Example/RxSegue.xcworkspace' -scheme 'RxSegue-Example' -configuration 'Debug' -sdk iphonesimulator -destination platform='iOS Simulator',OS='10.0',name='iPhone 7' build test  | xcpretty -c --test
#- pod lib lint
